export const NOTIFICATION_TYPE = {
  ASSIGNMENT_CREATED: "ASSIGNMENT_CREATED",
  ASSIGNMENT_UPDATED: "ASSIGNMENT_UPDATED",
  ASSIGNMENT_CANCELLED: "ASSIGNMENT_CANCELLED",

  WORKOUT_COMPLETED: "WORKOUT_COMPLETED",
  WORKOUT_STARTED: "WORKOUT_STARTED",

  BODY_MEASUREMENT_CREATED: "BODY_MEASUREMENT_CREATED",
  BODY_MEASUREMENT_UPDATED: "BODY_MEASUREMENT_UPDATED",
  BODY_MEASUREMENT_DELETED: "BODY_MEASUREMENT_DELETED",
  SYSTEM: "SYSTEM",
} as const;
