export const NOTIFICATION_TYPE = {
  ASSIGNMENT_CREATED: "ASSIGNMENT_CREATED",
  ASSIGNMENT_UPDATED: "ASSIGNMENT_UPDATED",
  ASSIGNMENT_CANCELLED: "ASSIGNMENT_CANCELLED",

  WORKOUT_COMPLETED: "WORKOUT_COMPLETED",
  WORKOUT_STARTED: "WORKOUT_STARTED",

  SYSTEM: "SYSTEM",
} as const;
